use_frameworks!

platform :ios, '9.0'
#在 podfile 文件中增加 修改podfile不用clean
install! 'cocoapods', :disable_input_output_paths => true

target 'MJAiSearchPartSDK_Example' do
  pod 'MJAiSearchPartSDK', :path => '../'
  pod 'SDWebImage'
  
  
  
  target 'MJAiSearchPartSDK_Tests' do
    inherit! :search_paths
    
    
  end
end
